[theme]
base = "dark"
primaryColor = "#27E0A3"
backgroundColor = "#071A2E"
secondaryBackgroundColor = "#0E2844"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
